---
abstract: 'use data objects to clean strings'
author:
  - 'NOTBENH <NOTBENH@cpan.org>'
build_requires:
  Module::Build: 0.3601
configure_requires:
  ExtUtils::MakeMaker: 6.31
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.101900, CPAN::Meta::Converter version 2.101670'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: String-Clean
requires:
  Carp::Assert::More: 0
  Test::More: 0
  YAML: 0
version: 0.03
