--- #YAML:1.0
name:                String-Clean
version:             0.01
abstract:            use data objects to clean strings
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Carp::Assert::More:            0
    Test::More:                    0
    YAML:                          0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - ben hengst <notbenh@CPAN.org>
